---
- name: Ansible block
  hosts: usa
  gather_facts: yes
  become: yes

  vars:
    
    user_create:
      - { user_name: prdoracle, group_name: dba,    user_shell: /bin/bash }
      - { user_name: prdjboss,  group_name: jboss,  user_shell: /bin/csh  }
      - { user_name: prdtomcat, group_name: tomcat, user_shell: /bin/bash }

    group_name: [ dba, jboss, tomcat ] 
    
    status: present
    
  tasks:
  - block:
    - name: Create group for my app
      group:
        name: "{{ item }}"
        state: "{{ status }}"
      loop: "{{ group_name }}"
      
    - name: create app users
      user:
        name:  "{{ item.user_name   }}"
        group: "{{ item.group_name  }}"
        shell: "{{ item.user_shell  }}"
        state: "{{ status }}"
      loop: "{{ user_create }}"
    
    when: ansible_distribution == 'CentOS'
    
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: >
       ( ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7' )
        or 
       ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16' )
        or
       ( ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' )
  
  