---
- name: loop with register
  hosts: usa
  gather_facts: yes
  become: yes

  vars:
    check_http: ''
      
  tasks:
  - name: check sshd service before install httpd
    shell: systemctl is-active sshd
    register: check_sshd
    ignore_errors: true

  - name: install httpd
    yum:
      name: httpd
      state: present
    when: >
       ( ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7' )
        or 
       ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16' )
        or
       ( ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' )

  - name: install httpd
    yum:
      name: apache2
      state: present
    when: >
       ( ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7' )
        or 
       ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16' ) 
   
  
   
    
