- name: template
  hosts: usa
  gather_facts: no
  become: yes

  vars:
    ip_addr: 192.168.2.210
    prefix: 24
    gateway: 192.168.2.1
    dns: 192.168.2.52
    domain: telnetinfo.ca

  tasks:
  - name: update interface config file
    template:
      src: ifconfig_file.j2
      dest: /home/devops/ifconfig_ens192